float32 cpu_used # percent cpu utilization
float32 mem_used # percent memory used
float32 e_wall # volts
float32 e_batt1 # volts
float32 e_batt2 # volts
float32 e_bus # volts
float32 i_bus # amps
float32 t_internal # *C
float32 p_internal # Pa
float32 altitude # m
bool wall_avail
bool batt1_avail
bool batt2_avail
bool wall_active
bool batt1_active
bool batt2_active
bool power_switch
bool external_switch
